const COUNTRIES = [
  'United States',
  'Canada',
  'Mexico',
  'United Kingdom',
  'France',
  'Germany',
  'Italy',
  'Spain',
  'Russia',
  'China',
  'Japan',
  'India',
  'Austria',
  'Sweden',
  'United Arab Emirates',
  'Brazil',
  'Australia',
  'Argentina',
  'Nigeria',
  'South Africa',
  'Egypt',
  'Saudi Arabia',
  'Iran',
  'Turkey',
  'Indonesia',
  'Pakistan',
  'Bangladesh',
  'Philippines',
  'Ukraine',
  'Thailand',
  'Vietnam',
  'Myanmar',
  'South Korea',
  'Afghanistan',
  'Morocco',
  'Colombia',
  'Algeria',
  'Sudan',
  'Uzbekistan',
  'Peru',
  'Angola',
  'Mali',
  'Mozambique',
  'Ghana',
  'Yemen',
  'Nepal',
  'Venezuela',
  'Madagascar',
  'Cameroon',
  'North Korea',
  'Australia',
  'Taiwan',
  'Sri Lanka',
  'Burkina Faso',
  'Malaysia',
  'Mauritania',
  'Chile',
  'Kazakhstan',
  'Zambia',
  'Guatemala',
  'Ecuador',
  'Netherlands',
  'Syria',
  'Senegal',
  'Cambodia',
  'Chad',
  'Somalia',
  'Zimbabwe',
  'Rwanda',
  'Guinea',
  'Benin',
  'Tunisia',
  'Bolivia',
  'Belgium',
  'Haiti',
  'Cuba',
  'South Sudan',
  'Dominican Republic',
  'Czech Republic',
  'Greece',
  'Portugal',
  'Jordan',
  'Azerbaijan',
  'Hungary',
  'Belarus',
  'Tajikistan',
];

function biasedRandomIndex(length: number, bias: number): number {
  const randomValue = Math.random() ** bias;
  return Math.floor(randomValue * length);
}

function getBiasedRandomString(strings: string[], bias = 2): string {
  if (strings.length === 0) {
    throw new Error('The input array should not be empty.');
  }
  const index = biasedRandomIndex(strings.length, bias);
  return strings[index];
}

export function getRandomCountry(): string {
  return getBiasedRandomString(COUNTRIES);
}
